name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events on specified branches
  push:
    branches: [ "main" , "dev" ]

  # Allows the run of this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs
jobs:
  publish-docker-images:
    needs: build-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - "friendship-service"
          - "content-service"
          - "user-service"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build service ${{ matrix.service }}
        uses: DanySK/build-check-deploy-gradle-action@3.7.6
        with:
          should-run-codecov: false
          build-command: |
            if [ "${{ matrix.service }}" == "content-service" ]; then
            ./gradlew :${{ matrix.service }}:compileTypescript
            else
            ./gradlew :${{ matrix.service }}:assemble
            fi
          check-command: ":"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push ${{ matrix.service }} image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: |
            marcofontana17/asw-social-network-${{ matrix.service }}:latest
            marcofontana17/asw-social-network-${{ matrix.service }}:${{ github.sha }}
